apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
    environment: production
    team: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: gizawag/auth-service:latest
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: auth-service-configmap
            - secretRef:
                name: auth-service-secret
